### ISSUE TITLE
Client crashes when trying to reconnect after disconnect

### ISSUE THREAD

**Issue by bradpower7** [rienheuver/Obsidio#8]
Will crash when re-connecting to server after server stop, currently have to restart client

**Comment by rienheuver** [comment]
Looked into this, got about this far:
`SeaBattleScene.java:678` crashes because `blockadeMap` is still null. This means that `createMap()` in the same file hasn't been called yet. `createMap()` is called only in `SendMapPacket.java`, which is, I think, only executed when the server performs `PlayerManager.java:555` `pl.getPackets.sendBoard();`. 

So `sendBoard()` should be executed by the server before the player starts to render the seaBattleScene. However, the player starts rendering that, I believe, when the server sends a loginResponse, which it does on `PlayerManager.java:551`. Putting that call on 551 after 555 doesn't fix it, because something else will crash then.

The big question however is, why does this work the first time you connect to the server and not the second time? Something is probably not correctly reset when the server disconnects, but I haven't yet figured out what.

**Comment by rienheuver** [comment]
Alright, I think I just fixed it. When the server disconnects, the client indeed does not seem to clean up nicely. I added `scenes.clear()` in the `dispose()` method of `GameContext` on the client. So releasing a new client in a bit which shouldn't have this problem anymore.
